name: Run Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - $default-branch

jobs:
  main:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies by lockfile
        run: npm clean-install

      - uses: nrwl/nx-set-shas@v4

      - name: Lint & Build
        run: npx nx run-many --targets=lint,build
        
      - name: Format Check
        run: npx nx format:check
