name: Run Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - $default-branch

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies by lockfile
        run: npm clean-install

      - name: Cache application
        uses: actions/cache@v3
        with:
          key: 'application:${{github.sha}}'
          path: ./

  bundle:
    name: Build & Checks
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download cached application
        uses: actions/cache@v3
        with:
          key: 'application:${{github.sha}}'
          path: ./

      - uses: nrwl/nx-set-shas@v3

      - run: npx nx format:check
      - run: npx nx run-many --targets=lint,build
